name: Frontend Tests

on:
  push:
    branches:
      - qa
      - dev
  pull_request:
    branches:
      - qa
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas del frontend
        run: npm test